name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main, features]

jobs:
  build-and-test:
    name: Build, Test & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true

      - name: Download dependencies
        working-directory: ./server
        run: go mod download

      - name: Build
        working-directory: ./server
        run: go build ./...

      - name: Test
        working-directory: ./server
        run: go test ./...
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Vet
        working-directory: ./server
        run: go vet ./...

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: latest
          working-directory: server
